### ISSUE TITLE
Programmverwaltung

### ISSUE THREAD

**Issue by danielswiatek** [dlrg/landestool#2]
Implementiert werden soll eine Programmanmeldung. Ein Programmpunkt hat verschiedene Eigenschaften. Alle Programmpunkte sollen dann in einer Liste angezeigt werden können. 

- Programmname
- Kategorie
- Verantwortlicher
- Zeitpunkt
- Treffpunkt
- Ort (Am besten mit Google Maps verknüpft)
- Kosten (Am besten können mehrere hinzugefügt werden)
- Bezahlungsart (Bar, Rechnung, Vorkasse, Spende, Sponsoring)
- Spendenbescheinigung (wenn Spende)
- Entfernung
- Transport
- min. Teilnehmer
- max. Teilnehmer
- Altersbegrenzung
- Betreuer
- Referent / Ansprechpartner
- Bemerkung
- Helferinfo
- Info für die Medienredaktion
- Info für die Website

**Comment by supermomme** [comment]
Steht Programmanmeldung dafür, dass Teilnehmer sich zu Programmen anmelden sollen können oder dass Programme angemeldet werden können?
Wie soll die Darstellung für den Teilnehmer und wie für den Administrator aussehen?

**Comment by Torge** [comment]
Daniel hat das auch schon so weit umgesetzt. Es geht in erster Linie darum, dass Administratoren Programme anlegen und bearbeiten können. Später sollen sich Teilnehmende an den Programmen anmelden können.

**Comment by supermomme** [comment]
Dafür erstellen wir ein neues Issue
