### ISSUE TITLE
Foto Upload Server

### ISSUE THREAD

**Issue by shieraki** [dlrg/landestool#27]
Für Profilfotos des Users, müsste noch Server-seitig eingerichtet werden

**Comment by supermomme** [comment]
Ich habe [feathers-blob](https://github.com/feathersjs-ecosystem/feathers-blob) mit [fs-blob-store](https://github.com/feathersjs-ecosystem/feathers-blob) eingebaut. Die hochgeladenen Bilder werden im Ordner `uploads` gespeichert.
### Hochladen
Man lädt Bilder hoch, indem der service `upload` mit
```js
{
  uri: '<ein Bild>'
}
```
angesprochen wird.
Zurück bekommt man eine Id, das Bild und die größe des Bildes.
### Angucken
Ich habe ein kleine middleware geschrieben, in der man die Bilder direkt sehen kann. Das ermöglicht diese direkt in html einzubauen. Die middleware erreicht man unter `/api/file/<ID>` Die Id erhält man bei dem hochladen.
### Test
Getestet habe ich das mit folgendem Bildformaten:
- PNG
- SVG
- JPEG
- GIF

Ich habe automatische Tests für die middleware eingebaut.
Dort wird die erfolgreiche erhalten eines GIF Bildes und ein Fehlschlag bei einem falschem Dateinamen getestet.

**Comment by shieraki** [comment]
Super, danke!!
