### ISSUE TITLE
Benutzerverwaltung

### ISSUE THREAD

**Issue by danielswiatek** [dlrg/landestool#3]
Benutzer haben folgende Eigenschaften. 

- Email Adresse (required)
- Passwort (required)
- Firstname (required)
- Lastname (required)
- Handynummer (required)
- Geburtsdatum (required)
- Straße (required)
- PLZ (required)
- Ort (required)
- Geschlecht m/w (required)
- Essen (keine unverträglichkeiten, vegetarisch, vegan, glutenfrei) (required)
- Bemerkung
- Gliederung
- Arbeitsgruppe

**Comment by supermomme** [comment]
Man kann sich nun als Benutzer anmelden und Benutzer verwallten. Registrierung wird noch gemacht.
Es können nun folgende Angaben den Benutzer gegeben werden:

- email (benötigt, einzigartig)
- password (benötigt)
- firstname (benötigt)
- lastname (benötigt)
- phone (benötigt)
- birthday (benötigt)
- gender (benötigt, m/w)
- diet (benötigt, none/vegetarian/vegan/glutenfree)
- address
- - street (benötigt)
- - zip (benötigt)
- - city (benötigt)
- comment
- division
- workgroup
